### ISSUE TITLE
Program starts then crashes immediately (varjo xr 3)

### ISSUE THREAD

**Issue by TheRealTaylorXia** [clarte53/GaussianSplattingVRViewerUnity#1]
I am trying to use the Clarte VR Viewer with a Varjo XR 3 headset on Windows 10 with a point cloud I created using the original gaussian splatting research paper code. 

Upon executing the application I briefly see the Clarte splash screen then the program exits, presumably via an error. Is this a problem with my headset or the application itself? Is there any way I can view the unity crash logs? If so, I'll post one here ASAP. Sorry for the lack of detail.

Thank you!

**Comment by Peamon** [comment]
Hi,

Could you post the unity logs that you can found in `%appdata%\..\LocalLow\CLARTE\GaussianSplattingVRViewer` ?

Also, have you tried to launch the application **without** using your own `point_could.ply` file ? does it crash too ?

Best regards.

**Comment by MiG-Ui** [comment]
Hi,

The same headset and the same problem here. I tried first launching the application without any ply file and then with one and got the same result both times. I've attached the logs below.

Thank you!

<details><summary>Player.log</summary>
<p>
Mono path[0] = 'D:/GaussianSplattingVRViewer/ClarteGaussianSplattingVRViewer/GaussianSplattingVRViewer_Data/Managed'
Mono config path = 'D:/GaussianSplattingVRViewer/ClarteGaussianSplattingVRViewer/MonoBleedingEdge/etc'
[Physics::Module] Initialized MultithreadedJobDispatcher with 47 workers.
Initialize engine version: 2022.3.9f1 (ea401c316338)
[Subsystems] Discovering subsystems at path D:/GaussianSplattingVRViewer/ClarteGaussianSplattingVRViewer/GaussianSplattingVRViewer_Data/UnitySubsystems
[Subsystems] No descriptors matched for  examples in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json
[Subsystems] 1 'displays' descriptors matched in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  meshings in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json.
GfxDevice: creating device client; threaded=1; jobified=1
[XR] [56800] [19:05:28.647][Info   ] Available Layers: (0)
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 4090 (ID=0x2684)
    Vendor:   NVIDIA
    VRAM:     24156 MB
    Driver:   31.0.15.2802
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.084 seconds
- Finished resetting the current domain, in  0.001 seconds
XRGeneral Settings awakening...
[Subsystems] OpenXR XR Plugin successfully registered Provider for OpenXR Display
[Subsystems] OpenXR XR Plugin successfully registered Provider for OpenXR Input
[Subsystems] OpenXR XR Plugin successfully registered Provider for OpenXR Display
[Subsystems] Loading plugin UnityOpenXR for subsystem OpenXR Display...
[XR] [56800] [19:05:29.142][Info   ] Available Layers: (0)
[Subsystems] Loading plugin UnityOpenXR for subsystem OpenXR Input...
<RI> Initializing input.

New input system (experimental) initialized
Using Windows.Gaming.Input
<RI> Input initialized.

<RI> Initialized touch support.

[XR] [56800] [19:05:29.257][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_UNKNOWN->XR_SESSION_STATE_IDLE session=2630426206944 time=1000030542022338300
[XR] [56800] [19:05:29.257][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_IDLE->XR_SESSION_STATE_READY session=2630426206944 time=1000030542022458100
[XR] [20056] [19:05:29.448][Error  ] Failed to create swapchain, exiting session.
[XR] [56800] [19:05:29.448][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_READY->XR_SESSION_STATE_SYNCHRONIZED session=2630426206944 time=1000030542213356100
[XR] [56800] [19:05:29.448][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_SYNCHRONIZED->XR_SESSION_STATE_STOPPING session=2630426206944 time=1000030542213381000
[XR] [56800] [19:05:29.448][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_STOPPING->XR_SESSION_STATE_IDLE session=2630426206944 time=1000030542213485500
[XR] [56800] [19:05:29.448][Info   ] OpenXRSession::HandleSessionStateChangedEvent: state XR_SESSION_STATE_IDLE->XR_SESSION_STATE_EXITING session=2630426206944 time=1000030542213501000
Shutting down OpenXR.
[XR] [56800] [19:05:29.451][Error  ] xrRequestExitSession: XR_ERROR_SESSION_NOT_RUNNING
[XR] [56800] [19:05:29.452][Info   ] 

==== Start Unity OpenXR Diagnostic Report ====


[XR] [56800] [19:05:29.452][Info   ] ==== Report Reason: System Shutdown ====


[XR] [56800] [19:05:29.452][Info   ] ==== OpenXR Init Info ====
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Stage 1 Missing Entry Points: (1)
[XR] [56800] [19:05:29.452][Info   ]   xrInitializeLoaderKHR
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] ==== OpenXR Provider Info ====
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Spec Version: 1.0.27
[XR] [56800] [19:05:29.452][Info   ] Provider Version: 1.8.2
[XR] [56800] [19:05:29.452][Info   ] App: GaussianSplattingVRViewer #3118937138
[XR] [56800] [19:05:29.452][Info   ] Engine: 2022.3.9f1 #53515265
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] ==== OpenXR Runtime Info ====
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Features requested to be enabled: (1)
[XR] [56800] [19:05:29.452][Info   ]   Oculus Touch Controller Profile: Version=0.0.1, Company="Unity"
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Requested feature extensions not supported by runtime: (0)
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Available Runtime Extensions: (20)
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_D3D11_enable: Version=9
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_D3D12_enable: Version=9
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_opengl_enable: Version=10
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_win32_convert_performance_counter_time: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_composition_layer_depth: Version=6
[XR] [56800] [19:05:29.452][Info   ]   XR_EXT_eye_gaze_interaction: Version=2
[XR] [56800] [19:05:29.452][Info   ]   XR_VARJO_composition_layer_depth_test: Version=2
[XR] [56800] [19:05:29.452][Info   ]   XR_VARJO_environment_depth_estimation: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_EXT_debug_utils: Version=4
[XR] [56800] [19:05:29.452][Info   ]   XR_EXT_win32_appcontainer_compatible: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_VARJO_quad_views: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_VARJO_foveated_rendering: Version=2
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_visibility_mask: Version=2
[XR] [56800] [19:05:29.452][Info   ]   XR_EXT_hand_tracking: Version=4
[XR] [56800] [19:05:29.452][Info   ]   XR_VARJO_marker_tracking: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_HTCX_vive_tracker_interaction: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_VARJO_view_offset: Version=1
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_vulkan_enable: Version=8
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_vulkan_enable2: Version=2
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_swapchain_usage_input_attachment_bit: Version=3
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Available Layers: (0)
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Runtime Name: Varjo OpenXR Runtime
[XR] [56800] [19:05:29.452][Info   ] Runtime Version: 3.10.2
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Form factor: XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Runtime extensions enabled: (3)
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_D3D11_enable: Version=9
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_composition_layer_depth: Version=6
[XR] [56800] [19:05:29.452][Info   ]   XR_KHR_visibility_mask: Version=2
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Available Reference Spaces: (3)
[XR] [56800] [19:05:29.452][Info   ]   XR_REFERENCE_SPACE_TYPE_VIEW
[XR] [56800] [19:05:29.452][Info   ]   XR_REFERENCE_SPACE_TYPE_LOCAL
[XR] [56800] [19:05:29.452][Info   ]   XR_REFERENCE_SPACE_TYPE_STAGE
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Instance Id  : 0x90f0d60
[XR] [56800] [19:05:29.452][Info   ] System Id    : 0x1
[XR] [56800] [19:05:29.452][Info   ] Session Id   : 0x719ea2e0
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Available View Configuration Types: (1)
[XR] [56800] [19:05:29.452][Info   ]   XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO (Selected): FovMutable=False
[XR] [56800] [19:05:29.452][Info   ]     [0]: Recommended: Width=3140, Height=2692, SampleCount=1
[XR] [56800] [19:05:29.452][Info   ]     [0]:     Maximum: Width=3140, Height=3140, SampleCount=1
[XR] [56800] [19:05:29.452][Info   ]     [1]: Recommended: Width=3140, Height=2692, SampleCount=1
[XR] [56800] [19:05:29.452][Info   ]     [1]:     Maximum: Width=3140, Height=3140, SampleCount=1
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Skip Present To Main Screen: No
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Available Environment Blend Modes: (2)
[XR] [56800] [19:05:29.452][Info   ]   XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND (Selected)
[XR] [56800] [19:05:29.452][Info   ]   XR_ENVIRONMENT_BLEND_MODE_OPAQUE
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] System Properties: Name="XR-3", VendorId=7750
[XR] [56800] [19:05:29.452][Info   ] System Graphics Properties: MaxWidth=16384, MaxHeight=16384, MaxLayers=16
[XR] [56800] [19:05:29.452][Info   ] System Tracking Properties: OrientationTracking=True, PositionTracking=True
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] ==== OpenXR Input ====
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] Action Sets (1): 
[XR] [56800] [19:05:29.452][Info   ]   oculustouchcontroller: ActionCount=17
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] ==== Last 20 non-XR_SUCCESS returns ====
[XR] [56800] [19:05:29.452][Info   ] [FAILURE] xrRequestExitSession: XR_ERROR_SESSION_NOT_RUNNING (1x)
[XR] [56800] [19:05:29.452][Info   ] 
[XR] [56800] [19:05:29.452][Info   ] ==== Last 20 Events ====
[XR] [56800] [19:05:29.452][Info   ] XrEventDataSessionStateChanged: XR_SESSION_STATE_UNKNOWN->XR_SESSION_STATE_IDLE
[XR] [56800] [19:05:29.452][Info   ] XrEventDataSessionStateChanged: XR_SESSION_STATE_IDLE->XR_SESSION_STATE_READY
[XR] [56800] [19:05:29.452][Info   ] XrEventDataSessionStateChanged: XR_SESSION_STATE_READY->XR_SESSION_STATE_SYNCHRONIZED
[XR] [56800] [19:05:29.452][Info   ] XrEventDataSessionStateChanged: XR_SESSION_STATE_SYNCHRONIZED->XR_SESSION_STATE_STOPPING
[XR] [56800] [19:05:29.452][Info   ] XrEventDataSessionStateChanged: XR_SESSION_STATE_STOPPING->XR_SESSION_STATE_IDLE
[XR] [56800] [19:05:29.452][Info   ] XrEventDataSessionStateChanged: XR_SESSION_STATE_IDLE->XR_SESSION_STATE_EXITING
[XR] [56800] [19:05:29.452][Info   ] 

==== End Unity OpenXR Diagnostic Report ====


UnloadTime: 0.559800 ms
Setting up 24 worker threads for Enlighten.
Memory Statistics:
[ALLOC_TEMP_TLS] TLS Allocator
  StackAllocators : 
    [ALLOC_TEMP_MAIN]
      Peak usage frame count: [0-1.0 KB]: 1 frames, [8.0 KB-16.0 KB]: 1 frames, [0.5 MB-1.0 MB]: 1 frames, [2.0 MB-4.0 MB]: 1 frames
      Initial Block Size 4.0 MB
      Current Block Size 4.0 MB
      Peak Allocated Bytes 2.1 MB
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 38]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 4]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Loading.PreloadManager]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 125.1 KB
      Overflow Count 4
    [ALLOC_TEMP_Job.worker 44]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 11]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 32]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 37]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 30]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 27]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 40]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 6]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 16]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 3]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 19]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 12]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 2]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 10]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 7]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 15]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 5]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 96 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 43]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 20]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 23]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 8]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 39]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 13]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_AssetGarbageCollectorHelper] x 47
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 138 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 46]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 33]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 0]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 28]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 6]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 8]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 112 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 36]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 14]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_HIDInput]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 10.9 KB
      Overflow Count 0
    [ALLOC_TEMP_BatchDeleteObjects]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 26]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 31]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 11]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 15]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 45]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 9]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 0]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 4]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 14]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 13]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 1]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_EnlightenWorker] x 24
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 1]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 3.1 KB
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 21]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 3]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 25]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.worker 5]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 12]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_UnityGfxDeviceWorker]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 2.8 KB
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 22]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 35]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 2]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0.8 KB
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 10]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 7]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 17]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 29]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 42]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 9]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 18]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 34]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 24]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.worker 41]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Loading.AsyncRead]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 369 B
      Overflow Count 0
[ALLOC_DEFAULT] Dual Thread Allocator
  Peak main deferred allocation count 65
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.2 MB
    [ALLOC_DEFAULT_MAIN]
      Peak usage frame count: [16.0 MB-32.0 MB]: 4 frames
      Requested Block Size 16.0 MB
      Peak Block count 2
      Peak Allocated memory 26.4 MB
      Peak Large allocation bytes 8.0 MB
    [ALLOC_DEFAULT_THREAD]
      Peak usage frame count: [64.0 MB-128.0 MB]: 4 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 77.0 MB
      Peak Large allocation bytes 68.8 MB
[ALLOC_TEMP_JOB_1_FRAME]
  Initial Block Size 2.0 MB
  Used Block Count 0
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_2_FRAMES]
  Initial Block Size 2.0 MB
  Used Block Count 0
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_4_FRAMES (JobTemp)]
  Initial Block Size 2.0 MB
  Used Block Count 1
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_ASYNC (Background)]
  Initial Block Size 1.0 MB
  Used Block Count 1
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_GFX] Dual Thread Allocator
  Peak main deferred allocation count 2
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.2 MB
    [ALLOC_GFX_MAIN]
      Peak usage frame count: [32.0 KB-64.0 KB]: 3 frames, [64.0 KB-128.0 KB]: 1 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 112.3 KB
      Peak Large allocation bytes 0 B
    [ALLOC_GFX_THREAD]
      Peak usage frame count: [32.0 KB-64.0 KB]: 2 frames, [128.0 KB-256.0 KB]: 2 frames
      Requested Block Size 16.0 MB
      Peak Block count 1
      Peak Allocated memory 166.3 KB
      Peak Large allocation bytes 0 B
[ALLOC_CACHEOBJECTS] Dual Thread Allocator
  Peak main deferred allocation count 2
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.2 MB
    [ALLOC_CACHEOBJECTS_MAIN]
      Peak usage frame count: [1.0 MB-2.0 MB]: 4 frames
      Requested Block Size 4.0 MB
      Peak Block count 1
      Peak Allocated memory 1.1 MB
      Peak Large allocation bytes 0 B
    [ALLOC_CACHEOBJECTS_THREAD]
      Peak usage frame count: [1.0 MB-2.0 MB]: 3 frames, [2.0 MB-4.0 MB]: 1 frames
      Requested Block Size 4.0 MB
      Peak Block count 1
      Peak Allocated memory 2.7 MB
      Peak Large allocation bytes 0 B
[ALLOC_TYPETREE] Dual Thread Allocator
  Peak main deferred allocation count 0
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 1.2 MB
    [ALLOC_TYPETREE_MAIN]
      Peak usage frame count: [4.0 KB-8.0 KB]: 4 frames
      Requested Block Size 2.0 MB
      Peak Block count 1
      Peak Allocated memory 5.2 KB
      Peak Large allocation bytes 0 B
    [ALLOC_TYPETREE_THREAD]
      Peak usage frame count: [16.0 KB-32.0 KB]: 4 frames
      Requested Block Size 2.0 MB
      Peak Block count 1
      Peak Allocated memory 20.4 KB
      Peak Large allocation bytes 0 B
</p>
</details>

**Comment by TheRealTaylorXia** [comment]
Hello Peamon, thank you for the fast response, I really appreciate it!

I'm still having trouble finding the unity logs unfortunately - I can't seem to find a LocalLow or CLARTE folder in my roaming directory. I also searched for a player.log such as the one MiG-Ui produced but I haven't found anything.

I did try running the viewer application both with and without my generated point cloud file, both produce the same outcome or seeing the splash screen briefly then crashing. 

If you need anything else or any more info please let me know!
Thank you!

**Comment by Peamon** [comment]
I Will Check this on our varjo headset on Monday and will give you a feedback.

**Comment by Peamon** [comment]
From the [varjo documentation](https://developer.varjo.com/docs/unity-xr-sdk/getting-started-with-varjo-xr-plugin-for-unity)

![IMG_5744](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/d2740ea7-f8e9-4fd7-99b4-c72b81735f15)

Openxr from unity is not supported. I will do a varjo specific build on Monday.

**Comment by Peamon** [comment]
### Solution
Hi, i have found the solution. It's because Varjo does not support "Depth Submission" . @TheRealTaylorXia  @MiG-Ui 

I just posted a new build [ClarteGaussianSplattingVRViewer-NoDepthSub.zip](https://github.com/clarte53/GaussianSplattingVRViewerUnity/releases/download/v1.1/ClarteGaussianSplattingVRViewer-NoDepthSub.zip) in [Releases](https://github.com/clarte53/GaussianSplattingVRViewerUnity/releases).

Let me know if it works for you.

### For Developpers

For Varjo, this option have to be set to `None`
![depth_submission](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/ef34d130-77cc-4cc4-b43d-84b2ea36db4b)

**Comment by MiG-Ui** [comment]
Hi, the build you posted works perfectly for me and it looks great.
Thanks again!
