### ISSUE TITLE
Can this support multipy ply files rendering in the same time?

### ISSUE THREAD

**Issue by lucylucy27** [clarte53/GaussianSplattingVRViewerUnity#10]
I duplicate the 'Gaussian Splatting' in the scene GaussianSplattingCam and play in editor to try rendering different ply files.
But the editor hints: illegal memory access.
Does this lib support mutiply thread rendering?

**Comment by Peamon** [comment]
Check this: https://github.com/clarte53/GaussianSplattingVRViewerUnity/issues/2

But for performance, the best way to display 2 ply file is to concatenate in one before rendering it.

Feel free to modify the base library to do this and make a pull request.
