### ISSUE TITLE
Run without an HMD

### ISSUE THREAD

**Issue by sjdingcn** [clarte53/GaussianSplattingVRViewerUnity#13]
Hi,
Is there a way to run this project without an HMD?
I am using a Win PC and want to make some 3DGS to show in this Unity Viewer.
Can I see the result directly on my PC or an Android phone?

Many thanks

**Comment by Peamon** [comment]
Yes you can see it on pc, if you clone the repository and open the unity project, you can open the scene `GaussianSplattingCam`. That is an example of using the plugin in unity player.

It will not work on an android phone because it use CUDA.
