### ISSUE TITLE
how test your depth support and transparency ? 

### ISSUE THREAD

**Issue by goometasoft** [clarte53/GaussianSplattingVRViewerUnity#15]
thank your VRViewerUnity , i like it very much !

how test your depth support and transparency to have a fully integrable plugins for rendering in unity ?

**Comment by Peamon** [comment]
I’m developing this currently. I will post a message when work is done. Soon I hope.

**Comment by Peamon** [comment]
Depth is now merged with the camera in this new version [v1.2](https://github.com/clarte53/GaussianSplattingVRViewerUnity/tree/v1.2).

The merge is done before the transparency pass. and Gaussian transparency is correctly mixed with opacity pass result.
