### ISSUE TITLE
Increase max scaling limit and fix viewing for large models

### ISSUE THREAD

**Issue by ghornig** [clarte53/GaussianSplattingVRViewerUnity#16]
Hey, love the splat viewer. It's definitely the easiest way to view splats in VR. 

I have a feature request: I sometimes find myself working with models that need to be scaled to large sizes to be accurate. The splat might start out with the model being the 10's of cm across, but in reality it needs to be 2+ meters to be accurately sized (like a car or building for example.)
However when I scale things up large, it seems like scaling doesn't work linearly and at a certain point trying to increase scale doesn't do much anymore. Also weird clipping occurs with my 'eyes' when trying to get close to largely scaled models. Almost as though my headset is getting in the way of viewing it close enough. Ideal behavior would be to size something large and then be able to interact with it like it was actually that size. Thanks!

**Comment by Peamon** [comment]
Thanks.

Yes, it's a known problem.

Actually the scale is managed in a weird way, it does not really scale the gaussian but apply the inverse scale to the point of view. So, when you scale up, too much it create all the problem you are describing. also the near clip is fixed and not multiplied by invert scaled factor as it should be so when you scale up it's like you have a near clip multiplicated by scale factor.

I'm working currently on a new version that integrate scale in the view matrix to avoid this problem.

Keep on track, it will be pushed soon.

**Comment by ghornig** [comment]
Thanks, looking forward to it!

**Comment by Peamon** [comment]
The new version [v1.2](https://github.com/clarte53/GaussianSplattingVRViewerUnity/tree/v1.2) has fixed the scale issue and the near and far clip one too.
