### ISSUE TITLE
Feature: Cycle through multiple point_cloud.ply

### ISSUE THREAD

**Issue by Bardo-Konrad** [clarte53/GaussianSplattingVRViewerUnity#17]
Cycle through multiple `point_cloud.ply` in a `list.txt`

So you have a `list.txt` in `GaussianSplattingVRViewer.exe`'s folder and in this there is

```
path\to\point_cloud.ply
path2\to\point_cloud.ply
...
```

And you can cycle through them using the joystick, fi by holding trigger and using the joystick.

**Comment by Peamon** [comment]
In the new version [v1.2](https://github.com/clarte53/GaussianSplattingVRViewerUnity/tree/v1.2), all the "*.ply" file near the exe are listed and you can cycle to each in the menu.

**Comment by Bardo-Konrad** [comment]
The problem with your approach is that you have to copy/link all files and they cloud up the folder. Besides, you cannot copy multiple point_cloud.ply next to each other. By using my appraoch, you also know where they came from, as "point_cloud.ply" does not say anything about the specific content, but the folder normally does.
