### ISSUE TITLE
Feature: Set floor and height

### ISSUE THREAD

**Issue by Bardo-Konrad** [clarte53/GaussianSplattingVRViewerUnity#18]
When loading a new model, 

1. set the floor. That means you move the model till you can see the floor. Then you point at three separate points on the floor. Based on this, the model is aligned in yaw, pitch and roll and the floor set at the user's floor
2. set height. That means, you point at something that should be at eye level, and the model is scaled accordingly.
3. This is saved at best in the ply, so next time you load the ply, it is already aligned.

All alignments should be correctable.

When loading a known model, load the data from the ply to align.

**Comment by Peamon** [comment]
Build proposed is just an example of how to use the plugin.

Feel free to clone and modify the unity projet for your own purpose.

**Comment by Bardo-Konrad** [comment]
It's your idea and your project, why not implement the neat feature I suggested and improve your project?

I have a lot of projects, each with individual challenges, I do not want another one, and you are already versed using the plugin and unity...
