### ISSUE TITLE
Can not add my own .ply 

### ISSUE THREAD

**Issue by JonaTh4nX** [clarte53/GaussianSplattingVRViewerUnity#21]
Hi there, 

Is there a way to properly use our own .ply file ?

**Comment by Peamon** [comment]
Yes just put it near the '.exe' file.

https://github.com/clarte53/GaussianSplattingVRViewerUnity?tab=readme-ov-file#loading-an-other-model

**Comment by JonaTh4nX** [comment]
My bad, I was talking about the unity version project 
(but yes, this works for .exe version)

**Comment by Peamon** [comment]
Just add a new gameobject attach a GaussianSplattingModel script and set the file path.

https://github.com/clarte53/GaussianSplattingVRViewerUnity/tree/master/GaussianSplattingVRViewer#gaussian-splatting-model-script

**Comment by JonaTh4nX** [comment]
Cheers mate !
