### ISSUE TITLE
No images in HMD display

### ISSUE THREAD

**Issue by YingJiang96** [clarte53/GaussianSplattingVRViewerUnity#3]
The project is so awesome! I love it! May I konw the detailed configuration of build setting and project setting? I did succeed running the program while there is no images or scenes in my PC and HMD display. I am pretty sure that it has already generated the tex under Tex/Element0, Element1，and the texture can update when I move(rotate or transform) my HMD. However, I am still so lost why these are no images/display in my HMD and PC screen. I guess it might be related with the configurations? Many thanks. Hope to get your reply soon. Thanks a lot.

**Comment by Peamon** [comment]
Hi,

**What is your headset ? Is your headset configured as default OpenXR ?**

If i do not connect my headset or not define it as default OpenXR, it seem to have the same as you discribe :
![no_headset](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/94cc3dab-03da-4fa0-9acd-0d50a7fb8efd)

You can check if your heaset is correctly connected in deactivating the "GaussianSplattingBlit" script on camera. When this script is deactivated you should see the skybox and should be able to move. If the sky box is not moving while moving the headset, is't a problem in headset configuration for OpenXR.
![deactivate_blit](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/1709f7d9-b1ef-4a17-9a15-721562c69c88)

For information here is my openXR pref
![openxr_parameters](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/d8674938-75a5-47f4-8e17-53c2f516b665)

and my player pref
![player_pref](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/b27c74ff-a831-4632-9e1f-098e1c9dfc92)

**Comment by Peamon** [comment]
An Other reason can be that you forget to download 'default_mode.bytes' like explained in the [README/Starting](https://github.com/clarte53/GaussianSplattingVRViewerUnity/blob/master/GaussianSplattingVRViewer/README.md#starting). In this case you should see `Missing (Text Asset)` like below. Just download the [default_model.bytes](https://github.com/clarte53/GaussianSplattingVRViewerUnity/releases) put it in your Assets directory and drag and drop it to the `Missing (Text Asset)`.
![missing_asset](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/36283606/3e8575be-2947-4ecf-a1c6-261d42900690)

**Comment by YingJiang96** [comment]
Thanks for your quick reply. My HMD is Quest2 and I downloaded the model.bytes as well. I created a new scene from VR template in the same project for testing. It works. I guess it might be some configure issues. Thanks for offering your configuraiton of openXR.

**Comment by Peamon** [comment]
Glad that you’ve found a solution.
Enjoy Gaussian splatting in VR.
