### ISSUE TITLE
 the Clarte startup screen appeared for 3 seconds then the full screen kept going black.

### ISSUE THREAD

**Issue by WillYao-THU** [clarte53/GaussianSplattingVRViewerUnity#6]
What a awesome project! So excited to find it! It's a pity that I haven't succeeded in implementing this project yet, so I really hope to get your help. Thanks a lot！

I've gotten the.ply file through Polycam and tried to see gaussian splatting on my pico neo3 headset. After connectted pico neo3 headset to Windows 10 PC using a USB cable, I launch the executable GaussianSplattingVRViewer.exe on Windows 10,  I see the Clarte startup screen for 3 seconds then the screen kept going black.
![image](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/135940893/c8fa19fb-3f92-4cbd-bc32-b96b6d48e17e)

More details:
1. the.ply file had been put in the same folder as the windows executable GaussianSplattingVRViewer.exe
![image](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/135940893/a757bad5-335e-4d3c-a3e4-6e33b9a7aa49)
2.  I also tried launching the GaussianSplattingVRViewer.exe without any ply file like:
![image](https://github.com/clarte53/GaussianSplattingVRViewerUnity/assets/135940893/7867cf9c-f102-4680-a760-d5f4ee936508)
3. I also tried the NoDepthSub version like the detail 1 and the detail 2, then got the same result（he Clarte startup screen for 3 seconds then the screen kept going black.
）
4. I didn't set headset's runtime as the default OpenXR runtime，because I can't find where to set

If you need more details, please feel free to contact me. Looking forward to your reply.

**Comment by Peamon** [comment]
Hi,

Your ply should be named "point_cloud.ply"

And pico neo3 seams to use steamvr (https://www.reddit.com/r/PicoXR/comments/116lyh6/pico_neo_3_link_and_openxr/)
So you have to set SteamVR as openxr by default : https://academy.vrex.no/knowledge-base/openxr/#steamvr

Tell me if it's ok now.

**Comment by WillYao-THU** [comment]
Hi,

Thank you very much for your timely help! Every piece hit the nail on the head! I finally got to see the stunning Gaussian splatting in VR. 

Thank you again for bringing such an awesome project！
