### ISSUE TITLE
Using gaussian splatting's alpha channel

### ISSUE THREAD

**Issue by hailsong** [clarte53/GaussianSplattingVRViewerUnity#7]
Thank you for the nice work! This repository gave me a lot of inspirations.

I wanna test object representation using gaussian splatting with this code.

What I wanna ask you is that, is there any way to get alpha channel of rendered results?
In the unity code, it seems that the rendered image from .dll file is sent to textures connected to XR Origin - Camera Offset - Main Camera. But the transparent parts looks black.

Can I modify it to transparent? (for example, showing unity's skybox or boundary scene when some part is empty...)

**Comment by Peamon** [comment]
For now, the Gaussian splatting rasteriser work in RGB so it force black pixel for the background. I will see if i can do someting for this but i'm not sure that is possible.

**Comment by hailsong** [comment]
Thank you for responding!
