### ISSUE TITLE
Last err message : illegal memory access when load & reload different scene data

### ISSUE THREAD

**Issue by lucylucy27** [clarte53/GaussianSplattingVRViewerUnity#8]
when i switch different modle files, it happens and stops at initialize.

**Comment by Peamon** [comment]
Could you post an example of a non working file ?

**Comment by lucylucy27** [comment]
Sorry it's My fault. It's fixed.

**Comment by AlKitChung** [comment]
Hi @lucylucy27 ,
We are also facing the same issue. Can you please let us know how you resolved it? Thank you.

**Comment by Mr-Kill** [comment]
Hi @lucylucy27 @AlKitChung ,
I am facing the same issue. Could you please provide the solutions you found? Thank you in advance.

**Comment by lucylucy27** [comment]
Not sure if we met the same issue，the code seems change a lot with my version. And I lost my copy.
Just for your reference -- I remember I added a reset() function to clear variables before opening another ply file.
